apiVersion: v1
kind: Service
metadata:  
  name: stage
spec:
  selector:    
    harness.io/color: Green
  type: LoadBalancer
  ports:  
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30008
