apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-green
  labels:
    env: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        env: green
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - green
      containers:
      - name: flask
        image: jcdemo/flaskapp:latest
        ports:
        - containerPort: 5000
